### ISSUE TITLE
请求帮助,安装了模块，调用如下，报错信息

### ISSUE THREAD

**Issue by liangxy-luf** [philip1134/pyzentao#2]
# _*_ coding: utf-8 _*_

import pyzentao

zentao = pyzentao.Zentao({
    "url": "http://chandao.xiongdi.com",
    "version": "15",
    "username": "admin",
    "password": "123456",
})

tasks = zentao.report_bugAssign()

print(tasks.status) # success
print(tasks.data)

----------------------------
报错信息如下：
Traceback (most recent call last):
  File "/pyzentaom.py", line 12, in <module>
    tasks = zentao.report_bugAssign()
  File "/lib/python3.7/site-packages/pyzentao/zentao.py", line 19, in _api
    return self.request(api, **kwargs)
  File "/lib/python3.7/site-packages/pyzentao/zentao.py", line 47, in request
    self.session.connect()
  File "lib/python3.7/site-packages/pyzentao/session.py", line 39, in connect
    self.connected = self._get_session() and self._login()
  File "lib/python3.7/site-packages/pyzentao/session.py", line 50, in _get_session
    response = resp.json()
  File "lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/yichu/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/yichu/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/yichu/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by philip1134** [comment]
这个报错一般是返回了html（通常是404页面），貌似在init的地方那个url需要加上zentao的路径：
zentao = pyzentao.Zentao({
**"url": "http://chandao.xiongdi.com",**
...
})
比如我的禅道API网址是 http://foo.bar/zentao/report_bugAssignxxxxxx
那么url就设置成"url": "http://chandao.xiongdi.com/zentao"，你试一下

抱歉我readme example写的比较草率。。。

**Comment by liangxy-luf** [comment]
感谢！！
